// packages/vue-test/src/App.vue
<script setup lang="ts">

import {ref} from "vue";
import {EASE, Transition} from "crossani";
import vCrossani from "@crossani/vue";

const transitions = {
  default: {
    reset: true,
    ms: 500,
  },

  step1: {
    state: {
      "background-color": "blue",
      border: "2px dashed red",
    },
    ms: 250,
    easing: EASE.linear,
  },

  step2: {
    state: {
      width: "250px",
      height: "90px",
    },
    ms: 300,
    easing: EASE.in,
  },

  step3: {
    state: {
      transform: "rotate(170deg)",
      "margin-left": "15rem",
    },
    ms: 600,
    easing: EASE.out,
  },
};

const step4 = {
  state: {
    background: "radial-gradient(circle at 110px, red, green)",
    "border-radius": "50%",
    "box-shadow": "0 0 10px black",
    transform: "rotate(170deg) translateX(50px) skewY(40deg)",
  },
  ms: 150,
  easing: EASE.startSteps(2),
};

const trigger = ref<string | Transition>("");
const current = ref<string | Transition | undefined>();

async function triggerAnimation() {
  trigger.value = "step1";
  await Promise.resolve(); // microtask abuse
  trigger.value = "step2";
  await Promise.resolve();
  trigger.value = "step3";
  await Promise.resolve();
  trigger.value = step4;
}

</script>

<template>

  <div style="gap: .25rem; display: flex">

    <button @click="triggerAnimation">trigger</button>
    <button @click="trigger = 'default'">reset</button>

    <template v-if="typeof current !== 'object'">{{ current }}</template>
    <em v-else-if="current === null">Not currently animating</em>
    <em v-else>Custom animation</em>


  </div>

  <div
      v-crossani="[transitions, trigger]"
      @animated="v => current = v.detail"
      :style="{
          backgroundColor: 'red',
          width: '100px',
          height: '100px',
          border: '5px solid blue',
          marginTop: '1rem'
        }"
  />

</template>

// packages/svelte-test/src/App.svelte
<script lang="ts">
	import { EASE } from "crossani";
	import crossani from "@crossani/svelte";
	import { tick } from "svelte";

	const transitions = {
		default: {
			reset: true,
			ms: 500,
		},

		step1: {
			state: {
				"background-color": "blue",
				border: "2px dashed red",
			},
			ms: 250,
			easing: EASE.linear,
		},

		step2: {
			state: {
				width: "250px",
				height: "90px",
			},
			ms: 300,
			easing: EASE.in,
		},

		step3: {
			state: {
				transform: "rotate(170deg)",
				"margin-left": "15rem",
			},
			ms: 600,
			easing: EASE.out,
		},
	};

	const step4 = {
		state: {
			background: "radial-gradient(circle at 110px, red, green)",
			"border-radius": "50%",
			"box-shadow": "0 0 10px black",
			transform: "rotate(170deg) translateX(50px) skewY(40deg)",
		},
		ms: 150,
		easing: EASE.startSteps(2),
	};

	let trigger, current;

	async function triggerAnimation() {
		trigger = "step1";
		await tick();
		trigger = "step2";
		await tick();
		trigger = "step3";
		await tick();
		trigger = step4;
	}
</script>

<div style:gap=".25em" style:display="flex">

  <button on:click={triggerAnimation}>trigger</button>
  <button on:click={() => trigger = "default"}>reset</button>

  {#if typeof current === "object"}
    <em>Custom animation</em>
  {:else if current !== undefined}
    {current}
  {:else}
    <em>Not currently animating</em>
  {/if}

</div>

<div
  use:crossani={[trigger, (c) => current = c, transitions]}

  style:background-color="red"
  style:width="100px"
  style:height="100px"
  style:border="5px solid blue"
  style:margin-top="1rem"
></div>
